### ISSUE TITLE
Treat COMPONENT keyword differently so it doesn't line break 

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#10]
Currently in my CMakeLists.txt there is something like

```
install(TARGETS ${PROJECT_NAME}
          EXPORT ${CMAKE_PROJECT_NAME}Targets
          ARCHIVE DESTINATION lib COMPONENT install-app
          LIBRARY DESTINATION lib COMPONENT install-app
          RUNTIME DESTINATION bin COMPONENT install-app)
```

After reformatting by cmake-format it becomes 

```
install(TARGETS ${PROJECT_NAME}
          EXPORT ${CMAKE_PROJECT_NAME}Targets
          ARCHIVE DESTINATION lib
          COMPONENT install-app
          LIBRARY DESTINATION lib
          COMPONENT install-app
          RUNTIME DESTINATION bin
          COMPONENT install-app)
```

which imo is less readable. Is it possible to treat the COMPONENT keyword differently so it doesn't line break ?

**Comment by cheshirekow** [comment]
You might get the behavior your want if you increase `max_subargs_per_line` which defaults to `3`. In this case I think the rule in play is that there are enough kwargs such that all kwargs will be given their own newline. Also, try overriding the builtin behavior with the following in your configuration (untested, but let me know if it does what you want). This is the same as the builtin configuration for the `install` command, minus the `COMPONENT` kwarg.

yaml:
```
additional_commands:
  install:
    flags: [NAMELINK_ONLY, NAMELINK_SKIP, OPTIONAL,
            USE_SOURCE_PERMISSIONS]
    kwargs: 
      ARCHIVE: .*
      BUNDLE: .*
      CONFIGURATIONS: .*
      DIRECTORY: .*
      DIRECTORY_PERMISSIONS: .*
      EXPORT: .*
      FILES: .*
      FILES_MATCHING: .*
      FILE_PERMISSIONS: .*
      FRAMEWORK: .*
      INCLUDESPERMISSIONS: .*
      LIBRARY: .*
      PRIVATE_HEADER: .*
      PROGRAMS: .*
      PUBLIC_HEADER: .*
      RENAME: .*
      RESOURCE: .*
      RUNTIME: .*
      TARGETS: .*
```

json:
```
"additional_commands": {
  "install",
    "flags" : ["NAMELINK_ONLY", "NAMELINK_SKIP", "OPTIONAL",
               "USE_SOURCE_PERMISSIONS"],
    "kwargs" : {
      "ARCHIVE": ".*",
      "BUNDLE": ".*",
      "COMPONENT": ".*",
      "CONFIGURATIONS": ".*",
      "DIRECTORY": ".*",
      "DIRECTORY_PERMISSIONS": ".*",
      "EXPORT": ".*",
      "FILES": ".*",
      "FILES_MATCHING": ".*",
      "FILE_PERMISSIONS": ".*",
      "FRAMEWORK": ".*",
      "INCLUDESPERMISSIONS": ".*",
      "LIBRARY": ".*",
      "PRIVATE_HEADER": ".*",
      "PROGRAMS": ".*",
      "PUBLIC_HEADER": ".*",
      "RENAME": ".*",
      "RESOURCE": ".*",
      "RUNTIME": ".*",
      "TARGETS": ".*"
  }
}
```
