### ISSUE TITLE
Spelling not accounted for

### ISSUE THREAD

**Issue by johelegp** [cheshirekow/cmake_format#202]
With part of my configuration file as:
```yaml
parse:
  additional_commands:
    CPMFindPackage:
      pargs:
        nargs: '*'
        flags: []
      spelling: CPMFindPackage
      kwargs:
        NAME: 1
        VERSION: 1
        GIT_TAG: 1
        GIT_SHALLOW: 1
        DOWNLOAD_ONLY: 1
        GITHUB_REPOSITORY: 1
        GITLAB_REPOSITORY: 1
        SOURCE_DIR: 1
        DOWNLOAD_COMMAND: 1
        FIND_PACKAGE_ARGUMENTS: 1
        OPTIONS: +
```
The following CMake extract:
```CMake
CPMFindPackage(NAME range-v3
    GITHUB_REPOSITORY ericniebler/range-v3
    GIT_TAG master
    GIT_SHALLOW True)
CPMFindPackage(NAME fmt
    GITHUB_REPOSITORY fmtlib/fmt
    GIT_TAG master
    GIT_SHALLOW True)
CPMFindPackage(NAME mp-units
    GITHUB_REPOSITORY mpusz/units
    GIT_TAG master
    GIT_SHALLOW True
    DOWNLOAD_ONLY True)
```
Is formatted as follows:
```CMake
cpmfindpackage(
    NAME range-v3
    GITHUB_REPOSITORY ericniebler/range-v3
    GIT_TAG master
    GIT_SHALLOW True)
cpmfindpackage(
    NAME fmt
    GITHUB_REPOSITORY fmtlib/fmt
    GIT_TAG master
    GIT_SHALLOW True)
cpmfindpackage(
    NAME mp-units
    GITHUB_REPOSITORY mpusz/units
    GIT_TAG master
    GIT_SHALLOW True
    DOWNLOAD_ONLY True)
```
I would expect `CPMFindPackage`'s spelling to remain unchanged.
