### ISSUE TITLE
cmake-lint does not respect cmake-format options

### ISSUE THREAD

**Issue by skycaptain** [cheshirekow/cmake_format#240]
When running `cmake-lint` after `cmake-format` with the following configuration:

```yaml
format:
  dangle_parens: true
  dangle_align: prefix-indent
```

I'm getting an [C0307] Bad indentation error:

```cmake
target_compile_features(
    ${PROJECT_NAME}
    PRIVATE cxx_std_11
    )
```

```plain
tests/CMakeLists.txt:49,04: [C0307] Bad indentation:
    )
^----BodyNode: 1:0->StatementNode: 46:0->TreeNode: 49:4
```

Looks like `cmake-lint` does not respect the settings from the format section.
