### ISSUE TITLE
fix: disabling formatting locally breaks code

### ISSUE THREAD

**Issue by JohelEGP** [cheshirekow/cmake_format#297]
Input and expected output:
```CMake
try_compile( # cmake-format: off
  check "${CMAKE_BINARY_DIR}/JEGPCpp2"
  "_jegp_test.cpp"
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED YES
  CXX_EXTENSIONS NO) # cmake-format: on
```

Actual output:
```CMake
try_compile(
  # cmake-format: off







    )
  check "${CMAKE_BINARY_DIR}/JEGPCpp2"
  "_jegp_test.cpp"
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED YES
  CXX_EXTENSIONS NO) # cmake-format: on
```

Configuration:
```yaml
format:
  line_width: 120
  tab_size: 2
  max_subgroups_hwrap: 3
  max_pargs_hwrap: 6
  max_rows_cmdline: 2
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  min_prefix_chars: 8
  max_prefix_chars: 8
  max_lines_hwrap: 2
  line_ending: unix
  command_case: canonical
  keyword_case: unchanged
  always_wrap: []
  enable_sort: true
  autosort: true
  require_valid_layout: false
  layout_passes: {}
markup:
  enable_markup: false
```

Putting `# cmake-format: on` at the end of any other line within the balanced parentheses breaks formatting.
