### ISSUE TITLE
Specifying a config file in `pre-commit` hook GitHub actions

### ISSUE THREAD

**Issue by jhlegarreta** [cheshirekow/cmake_format#335]
I am trying to use `cmake_format` together with `pre-commit` and a GitHub Actions workdflow to check the format of some `CMake` code in the following repository:
https://github.com/SlicerDMRI/SlicerDMRI

I have checked that the action works beautifully by default; I would be interested in using a specific configuration file. According to the `pre-commit` docs:
https://pre-commit.com/#pre-commit-configyaml---hooks

I should use the `args` keyword to pass additional parameters to the hook in the `.pre-commit-config.yaml` file, i.e.
```
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
        args: [-c Utilities/CMakeFormat/config.yaml]
      - id: cmake-lint
        args: [-c Utilities/CMakeFormat/config.yaml]
```

However, the GitHub Action says that it cannot find the config file at issue:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/6606209443/job/17942184338#step:4:116

It seems a path-related issue, maybe due to the current working directory the pre-commit hook is expecting, but it is unclear to me where the relative path is.

I would also expect the path to be valid when running `pre-commit` locally.

What am I missing?

Thanks for maintaining this tool.
