### ISSUE TITLE
Possible improvement on formatting export 

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#59]
Currently in my CMakeLists.txt there is something like

```
export(TARGETS ${PROJECT_NAME}
       APPEND FILE ${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake)
```

After reformatting by cmake-format it becomes

```
export(TARGETS
       ${PROJECT_NAME}
       APPEND
       FILE
       ${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake)
```

which imo is less readable. Is it possible to change it so it doesn't line break on TARGETS and APPEND FILE?

**Comment by sanssecours** [comment]
> Is it possible to change it so it doesn't line break on TARGETS and APPEND FILE?

Yes, that is possible. To do that just add the command `export` to the dictionary `additional_commands` in your configuration file. For example, to improve the formatting of export in your project, save a file called `.cmake-format.yaml` with the following content:

```yaml
additional_commands:

  export:
    flags:
      - APPEND
      - EXPORT_LINK_INTERFACE_LIBRARIES
    kwargs:
      ANDROID_MK: 1
      EXPORT: 1
      FILE: 1
      NAMESPACE: 1
      PACKAGE: 1
      TARGETS: "+"
```

at the top level of your project. Afterwards the output of `cmake-format` for your example should look like this:

```cmake
export(TARGETS ${PROJECT_NAME}
       APPEND
       FILE ${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake)
```

. For more information, please take a look [here](https://github.com/cheshirekow/cmake_format#configuration). 

Since `export` is a builtin command I added a specification for the command to pull request #54.
