### ISSUE TITLE
Breaking in Quotes

### ISSUE THREAD

**Issue by wrightleft** [cheshirekow/cmake_format#86]
I have some compile time definitions I want to add to a target, but cmake-format mangles the CMakeList.txt such that Make gets very confused.

Input:
```
target_compile_definitions(foo PUBLIC BAR="Hello World" BAZZZZZZZZZZZZZZZZZZZZZZZ)
```
Output:
```
target_compile_definitions(
  foo
  PUBLIC
  BAR="Hello
  World"
  BAZZZZZZZZZZZZZZZZZZZZZZZ
)
```
Expected Output:
```
target_compile_definitions(
  foo
  PUBLIC
  BAR="Hello World"
  BAZZZZZZZZZZZZZZZZZZZZZZZ)
```

My configuration file:
```yaml
always_wrap: []
bullet_char: "*"
command_case: lower
dangle_parens: true
enable_markup: true
enum_char: .
fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$
first_comment_is_literal: false
keyword_case: unchanged
line_ending: unix
line_width: 80
literal_comment_pattern: null
max_subargs_per_line: 1
ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
tab_size: 2
```
The break in the definition is causing issues.
